export interface ButtonProps {
  buttonType: ButtonTypes
  buttonColor: ButtonColors
  label: string
}

export type ButtonTypes = 'Primary' | 'Secondary' | 'Outline' | 'Clear'

export type ButtonColors =
  | 'gray_1'
  | 'gray_2'
  | 'gray_3'
  | 'gray_4'
  | 'gray_5'
  | 'gray_6'
  | 'blue_8'
  | 'blue_24'
  | 'blue_40'
  | 'blue_64'
  | 'blue_100'
  | 'blue_gradient'
  | 'red_8'
  | 'red_24'
  | 'red_40'
  | 'red_64'
  | 'red_100'
  | 'red_gradient'
  | 'yellow_8'
  | 'yellow_24'
  | 'yellow_40'
  | 'yellow_64'
  | 'yellow_100'
  | 'yellow_gradient'
  | 'green_8'
  | 'green_24'
  | 'green_40'
  | 'green_64'
  | 'green_100'
  | 'green_gradient'
  | 'pink_8'
  | 'pink_24'
  | 'pink_40'
  | 'pink_64'
  | 'pink_100'
  | 'pink_gradient'
  | 'purple_8'
  | 'purple_24'
  | 'purple_40'
  | 'purple_64'
  | 'purple_100'
  | 'purple_gradient'
