import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { useSession, signIn, signOut } from 'next-auth/react'
import Image from 'next/image'

const Home: NextPage = () => {
  const { data } = useSession()
  return (
    <div style={{ background: 'rgba(0,0,0,0.3)', height: '100vh' }}>
      <Head>
        <title>Next App Typescript Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
      </Head>

      <nav>
        <Link href="/about">
          <a>About</a>
        </Link>
      </nav>

      <main>
        <h1>Home Page</h1>
        {data?.user ? (
          <>
            <p>{data.user.name}</p>
            <Image
              style={{
                borderRadius: '50%',
              }}
              src={data.user.image || ''}
              width={96}
              height={96}
              alt={`${data.user.name} Thumbnail`}
            />
            <p>Company : {data.user.company}</p>
            <p>Email : {data.user.email}</p>
            <p>Location : {data.user.location}</p>
            <p>Public Repos : {data.user.public_repos}</p>
            <p>
              Github Url:
              <a
                style={{ color: 'teal' }}
                href={data.user.html_url}
                target="_blank"
                rel="noreferrer"
              >
                Github
              </a>
            </p>
            <button
              type="button"
              className="btn-auth"
              onClick={() => signOut()}
            >
              Github Logout
            </button>
          </>
        ) : (
          <button type="button" className="btn-auth" onClick={() => signIn()}>
            Github Login
          </button>
        )}
      </main>

      <footer>
        <p>Footer</p>
      </footer>
    </div>
  )
}

export default Home
