import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { useSession, signIn, signOut } from 'next-auth/react'
import { User } from 'components'

const Home: NextPage = () => {
  const { data } = useSession()

  return (
    <div>
      <Head>
        <title>Next App Typescript Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
      </Head>

      <nav>
        <Link href="/about">
          <a>About</a>
        </Link>
      </nav>

      <main>
        <h1>Home Page</h1>
        {data?.user ? (
          <>
            <User
              thumbnail={
                data?.user?.image || 'http://via.placeholder.com/36x36'
              }
              username={data.user.name || 'Unnamed'}
            />
            <button
              type="button"
              className="btn-auth"
              onClick={() => signOut()}
            >
              Github Logout
            </button>
          </>
        ) : (
          <button type="button" className="btn-auth" onClick={() => signIn()}>
            Github Login
          </button>
        )}
      </main>

      <footer>
        <p>Footer</p>
      </footer>
    </div>
  )
}

export default Home
