#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Check Testing
yarn test || (
    echo '🔥🔥🔥 Test Check Failed. 🔥🔥🔥';
    false;
)

# Check Prettier standards
yarn check-format ||
(
    echo '🤢🤮🤢🤮 Prettier Check Failed. Run yarn format, add changes and try commit again. 🤢🤮🤢🤮';
    false;
)


# Check ESLint Standards
yarn check-lint ||
(
    echo '😤🏀👋😤 ESLint Check Failed. Make the required changes listed above, add changes and try to commit again. 😤🏀👋😤'
    false; 
)

echo '✅✅✅✅ CLEAR ✅✅✅✅'